#!/bin/bash
# Shared variables are consumed by the scripts that source this file.
# shellcheck disable=SC2034

REPO_SRC=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
STAGING_AREA=${STAGING_AREA:-$PWD/staging}
STAGING_AREA_DEPS=${STAGING_AREA_DEPS:-$STAGING_AREA/dependencies}
BUILDDIR=${BUILDDIR:-$REPO_SRC/build}
JOBS=${JOBS:--j8}
# Preserve make-style values; accept numeric overrides used by CI as well.
[[ $JOBS == -j* ]] || JOBS="-j$JOBS"
[[ ${JOBS#-j} =~ ^[1-9][0-9]*$ ]] || { echo "JOBS must be a positive integer or -jN" >&2; return 1; }
ARCH=${ARCH:-$(uname -m)}
case "$ARCH" in arm64|x86_64) ;; *) echo "Unsupported architecture: $ARCH" >&2; return 1 ;; esac
export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-11.0}

# Qt6 via aqtinstall (clang_64 universal binary)
QT_INSTALL_LOCATION=${QT_INSTALL_LOCATION:-$HOME/Qt}
QT_VERSION=${QT_VERSION:-6.8.3}
QT=${QT:-$QT_INSTALL_LOCATION/$QT_VERSION/macos}
QT_PATH=$QT/bin
QMAKE_BIN=$QT_PATH/qmake6

export PATH="${QT_PATH}:$PATH"

# Generated by install_macos_deps.sh for builds selecting this Qt SDK.
SCOPY_QT_INCLUDE_DIR="$STAGING_AREA/qt-include"

LIBSERIALPORT_BRANCH=master
LIBIIO_VERSION=v0.26
LIBAD9361_BRANCH=main
LIBAD9166_BRANCH=libad9166-iio-v0
LIBM2K_BRANCH=main
QWT_BRANCH=qwt-multiaxes-updated
LIBTINYIIOD_BRANCH=master
KDDOCK_BRANCH=2.2
ECM_BRANCH=v6.8.0
KARCHIVE_BRANCH=v6.8.0
GENALYZER_BRANCH=main
QCORO_BRANCH=v0.13.0
